services:
  master:
    build: .
    image: kvstore:local
    ports:
      - "9090:9090"
    environment:
      - KVSTORE_DIR=/app/master
      - KVSTORE_MEMSIZE=100000
      - KVSTORE_REPLICATIONMODE=MASTER
      - KVSTORE_SLAVEADDRESSES=http://slave1:9091,http://slave2:9092
      - SERVER_PORT=9090
    volumes:
      - ./master-storage:/app/master
    depends_on:
      - slave1
      - slave2

  slave1:
    image: kvstore:local
    ports:
      - "9091:9091"
    environment:
      - KVSTORE_DIR=/app/slave1
      - KVSTORE_MEMSIZE=100000
      - KVSTORE_REPLICATIONMODE=SLAVE
      - SERVER_PORT=9091
    volumes:
      - ./slave1-storage:/app/slave1

  slave2:
    image: kvstore:local
    ports:
      - "9092:9092"
    environment:
      - KVSTORE_DIR=/app/slave2
      - KVSTORE_MEMSIZE=100000
      - KVSTORE_REPLICATIONMODE=SLAVE
      - SERVER_PORT=9092
    volumes:
      - ./slave2-storage:/app/slave2