server.port=${SERVER_PORT:9090}
kvstore.dir=${KVSTORE_DIR:.}
kvstore.memSize=${KVSTORE_MEMSIZE:100000}
kvstore.replicationMode=${KVSTORE_REPLICATIONMODE:RAFT}
kvstore.nodeId=${KVSTORE_NODEID:http://localhost:${SERVER_PORT:9090}}
kvstore.peerAddresses=${KVSTORE_PEERADDRESSES:}
kvstore.slaveAddresses=${KVSTORE_SLAVEADDRESSES:}
kvstore.raft.heartbeatMs=${KVSTORE_RAFT_HEARTBEATMS:150}
kvstore.raft.electionMinMs=${KVSTORE_RAFT_ELECTIONMINMS:900}
kvstore.raft.electionMaxMs=${KVSTORE_RAFT_ELECTIONMAXMS:1800}