server.port=${SERVER_PORT:9090}
kvstore.dir=${KVSTORE_DIR:.}
kvstore.memSize=${KVSTORE_MEMSIZE:100000}
kvstore.replicationMode=${KVSTORE_REPLICATIONMODE:RAFT}
kvstore.nodeId=${KVSTORE_NODEID:http://localhost:${SERVER_PORT:9090}}
kvstore.peerAddresses=${KVSTORE_PEERADDRESSES:}
kvstore.slaveAddresses=${KVSTORE_SLAVEADDRESSES:}
kvstore.raft.heartbeatMs=${KVSTORE_RAFT_HEARTBEATMS:150}
kvstore.raft.electionMinMs=${KVSTORE_RAFT_ELECTIONMINMS:900}
kvstore.raft.electionMaxMs=${KVSTORE_RAFT_ELECTIONMAXMS:1800}

cluster.shard-id=${CLUSTER_SHARD_ID:shard-1}


# ========================================
# ????? bootstrap ? ?????? ?? ?????? ????!
# ========================================
cluster.bootstrap.enabled=${BOOTSTRAP:false}

# ????????? ????? ? ?????? ???? cluster.bootstrap.enabled=true
cluster.bootstrap.initial-shards[0].shardId=shard-1
cluster.bootstrap.initial-shards[0].members[0]=node1:9090
cluster.bootstrap.initial-shards[0].members[1]=node2:9091
cluster.bootstrap.initial-shards[0].members[2]=node3:9092

cluster.bootstrap.initial-shards[1].shardId=shard-2
cluster.bootstrap.initial-shards[1].members[0]=node4:9093
cluster.bootstrap.initial-shards[1].members[1]=node5:9094
cluster.bootstrap.initial-shards[1].members[2]=node6:9095

# ???? ???????????? ??? ?????? (???? ?? bootstrap-????)
cluster.join-address=${JOIN_ADDR:}
logging.pattern.console=%d{HH:mm:ss.SSS} %5p [%X{rid}] %c{1} - %m%n